
.DEFAULT_GOAL := test

.PHONY: run
run:
	@PYTHONPATH=. python3 run_length_encoding.py

.PHONY: test
test:
	@PYTHONPATH=. python3 run_length_encoding_test.py

.PHONY: clean
clean:
	@rm -rf __pycache__

