
.PHONY: hello
hello:
	@gprolog --consult-file hello.pl --query-goal 'query_example; halt'

.PHONY: contains
contains:
	@gprolog --consult-file contains.pl

.PHONY: fizz_buzz
fizz_buzz:
	@gprolog --consult-file fizz_buzz.pl --query-goal 'query_example; halt'

